---
title: A Cross-Analysis of Data Sets
author: 'A Group Has No Name'
date: '2022-04-04'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-04-04T14:56:18-04:00'
featuredVideo: ~
featuredImage: ~
---

The current data from the American National Elections Studies specifically covers 
not just the recent 2020 presidential election, but also measured numerous qualities/characteristics of a large sample of voters. Such measurements include (besides traditional measurements such as partisan affiliation) attitudes towards women, rural attitudes towards government, and child development (whether or not a child should be raised to be independent or reliant on authorities for instance). However, the current data set by itself does not provide enough information with the current data analysis to accurately depict the levels/attitudes towards a more authoritarian government.

To supplement this analysis, it may be beneficial to try and not necessarily measure the direct authoritarian attitudes within individual states based off of one election, but measure it throughout a period of time. Hence, we have decided to incorporate more data from the American National Elections Studies that covers other presidential elections, going all the way back to the 2000 presidential election. To clarify, this group will not go further into previous presidential elections before the year 2000 as certain variables of interest were not measured as in depth as desired for the current analysis.

Additionally, it was decided to exclude midterm elections during this period between 2000 to 2020 as it would be hard to properly quantify such attitudes during these midterms, not to mention the complexities of trying to measure out such authoritarian attitudes considering the scope of this class. While it would be fascinating to see shifts within attitudes towards government on a down-ballot basis, to properly gather all the data down to state/local elections would be again out of scope of this class.

These additional data sets specifically cover all presidential elections after (and including) 2000. They notably measure the same material (perhaps under different variables), in which when trying to combine all data sets, it might require redefining (aka mutating) certain variables to align with their future counterparts. While there is a file within these data sets that have compiled everything, there is the possibility that due to that compiled file being pre-cleaned, that it might exclude certain variables of interest that become significant in the future. Hence, throughout this process we have also been looking into the individual data sets for individual values that may be of interest as well. 

Though we haven't combined data sets we expect to do this within the next week.
Since some of the American National Elections Studies data sets from years 
2000 onward don't have keys or overlapping variables we plan to treat each
year as unique cross sections. In combining these data sets we plan to 
aggregate by state and then join it with the MIT data, which has now been 
cleaned, by state and year. 
